---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: api03
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-92e5af8d
  image_type: t1.micro
  image_id: ami-a1da00bc
  security_groups:
  - api01_production_default
  - api01_production_web
  - api01_production_web_tools
  external_host: ec2-54-207-1-68.sa-east-1.compute.amazonaws.com
  external_ip: 54.207.1.68
  internal_host: ip-172-31-25-102.sa-east-1.compute.internal
  internal_ip: 172.31.25.102
  zone: sa-east-1a
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
